### ISSUE TITLE
Feature request. How to get the last timeperiod only and more?

### ISSUE THREAD

**Issue by statgreen** [rOpenGov/pxweb#197]
Wonder if you could add a feature to ease the process to get the last 1-to-many timeperiods, intervals,  and also also irregular periods like 'latest,minus1,minus4,minus6,minus12'

:-) Lars

**Comment by MansMeg** [comment]
Thanks for the request! 

So I think this should work if you use a JSON query. Although it is not implemented in the pxweb interactive. The reason is that I do not  know what type of choices that are available through the API.

I have opened up issues at the pxweb repo of stat sweden, bet they have not responded for more than six months so I do not know if and when this would be possible from within the R package.

**Comment by MansMeg** [comment]
Alright. Now StatSweden has responeded that they will not provide this information through the API so hence I cannot do this in the interactive part until pxweb 2.0, but that is probably in 2021 at the earliest (according to Stat Sweden).
