### ISSUE TITLE
Column name for values have to be changed? 

### ISSUE THREAD

**Issue by jhuovari** [rOpenGov/pxweb#84]
At least dataset sbs_pen_7b1 includes variable named `value`, so there would be two columns named value. Could be `values` as in pxweb.

But better ideas to solve the problem, as this will break code?

**Comment by antagomir** [comment]
Compatibility with pxweb would be very useful here if we can't keep the name "value". Not sure what other solutions could be. Unless the corresponding variable names for sbs_pen_7b1 and other data sets could be somehow automatically picked in a general case and change 'value' into the corresponding variable name instead. But I guess this is not possible to implement in a reliable way. So I like the suggestion of using the name 'values' for our output.

**Comment by jhuovari** [comment]
I think that I could try to solve this with using VALUE (upper case), if in variable (dimension) name. Should have thought the possibility of value as a dimension name before. Then `values` would have been good solution, but changing now will have a big effect for everyone using the package. Maybe this dirty fix is better solution.

**Comment by antagomir** [comment]
For me the 'values' is ok. I also think that as long as no version has been in CRAN users should assume this is unstable development version. But if you already have lots of code using this and it will be a major problem I understand that as well. In that case I can accept your suggestion. My preference would be with 'values' however since playing with lower/uppercase is potentially confusing and compatibility with pxweb conventions would be a plus.

**Comment by jhuovari** [comment]
I can live the `values`. It is pretty easy to find and replace, when you know. But lets wait a bit, if other have comments. Then we can change for the `values`.

**Comment by MansMeg** [comment]
I really don't understand the problem? Should we do changes in pxweb or is this in another package?

**Comment by jhuovari** [comment]
Sorry, I didn't realize I was on pxweb-page. This is about eurostat-package.

Really sorry, I messed up.
